image: node:10.9.0 # Should match .nvmrc content

stages:
  - install
  - tests
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - node --version
  - npm --version
  - ls -alh

# Install stage

npm_install:
  tags: [shared-ci-docker]
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules
    expire_in: 3 hours
    name: "node_modules-$(sha1sum package-lock.json | cut -c1-7)"

# Tests stage

npm_test:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

npm_run_lint:
  tags: [shared-ci-docker]
  stage: tests
  script:
    - npm run lint

# Build stage

npm_run_build:
  tags: [shared-ci-docker]
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 2 days
    name: "build-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
    paths:
      - dist

# Deploy story book

build:
  tags: [shared-ci-docker]
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - build/

deploy:
  tags: [shared-ci-docker]
  stage: deploy
  dependencies:
    - build
  only:
    - master
  script:
    - npx --package netlify-cli netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_ACCESS_TOKEN  --dir=./build --prod
