variables:
  GIT_SUBMODULE_STRATEGY: recursive


deploy_dev:
  tags: [shared-ci-docker]
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: dev
    url: https://acir-front-dev.geo.paas.corp-cluster.com
  only:
    - master
  script:
    - git-push ssh://dokku@geo.paas.corp-cluster.com/acir-front-dev

deploy_staging:
  tags: [shared-ci-docker]
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: staging
    url: https://acir-front-staging.geo.paas.corp-cluster.com
  only:
    - master
  script:
    - git-push ssh://dokku@geo.paas.corp-cluster.com/acir-front-staging
  when: manual

deploy_test:
  tags: [shared-ci-docker]
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: dev
    url: https://acir-front-dev.geo.paas.corp-cluster.com
  only:
    - test
  script:
    - git-push ssh://dokku@geo.paas.corp-cluster.com/test-front