image: node:12.16.1 # Should match .nvmrc content

stages:
  - prepare
  - deploy

before_script:
  - node --version
  - npm --version
  - ls -alh

# Tests stage

Tests:
  before_script:
    - npm ci
  tags: [shared-ci-docker]
  stage: prepare
  script:
    - npm run test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

Lint:
  before_script:
    - npm ci
  tags: [shared-ci-docker]
  stage: prepare
  script:
    - npm run lint

Build:
  before_script:
    - npm ci
  tags: [shared-ci-docker]
  stage: prepare
  variables:
    PUBLIC_URL: "/admin/"
  script:
    - npm run build
  artifacts:
    expire_in: 3 days
    paths:
      - build/

.deploy: &deploy # Deploy template
  tags: [shared-ci-docker]
  stage: deploy
  when: manual
  variables:
    SITE_ID: "yournamehere.netlify.com"
  dependencies:
    - Build
  script:
    - mkdir ./tmp
    - mv ./build ./tmp/admin
    - mv ./tmp/admin/_* ./tmp
    - npm i -g netlify-cli
    - npx netlify deploy --site=$SITE_ID --auth=$NETLIFY_ACCESS_TOKEN  --dir=./tmp --prod

Deploy Dev (force): &deploy_predev
  <<: *deploy
  environment:
    name: dev
    url: https://terra-admin-dev.netlify.com/admin
  variables:
    SITE_ID: "terra-admin-dev.netlify.com"

Deploy Dev:
  <<: *deploy_predev
  only:
    - master
  when: always

Deploy QA:
  <<: *deploy
  only:
    - master
  environment:
    name: qa
    url: https://terra-admin-qa.netlify.com/admin
  variables:
    SITE_ID: "terra-admin-qa.netlify.com"

Deploy Staging:
  <<: *deploy
  only:
    - master
  environment:
    name: staging
    url: https://terra-admin-staging.netlify.com/admin
  variables:
    SITE_ID: "terra-admin-staging.netlify.com"

Deploy Prod:
  <<: *deploy
  only:
    - master
  environment:
    name: prod
    url: https://terra-admins.netlify.com/admin
  variables:
    SITE_ID: "terra-admin.netlify.com"
