deploy_dev:
  tags: [shared-ci-docker]
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: dev
    url: https://acir-front-dev.geo.paas.corp-cluster.com
  only:
    - master
  script:
    - git-push ssh://dokku@geo.paas.corp-cluster.com/acir-front-dev

deploy_staging:
  tags: [shared-ci-docker]
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: staging
    url: https://acir-front-staging.geo.paas.corp-cluster.com
  only:
    - tags
  script:
    - git-push ssh://dokku@geo.paas.corp-cluster.com/acir-front-staging
    # prepare ssh access
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "geo.paas.corp-cluster.com" >> ~/.ssh/known_hosts
      # create tag
    - ssh dokku@geo.paas.corp-cluster.com tags:create acir-front-staging $CI_COMMIT_TAG
  when: manual
