# .github/workflows/netlify.yml
name: Build and deploy

# Controls when the action will run. 
on:  
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need tags for git describe

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install -g npm && npm rebuild node-sass
      - run: npm ci && npm rebuild node-sass && npm run build
        env:
          PUBLIC_URL: "/admin/"
      - run: |
          mkdir ./tmp
          mv ./build ./tmp/admin
          mv ./tmp/admin/_* ./tmp/
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: latest-build
          path: tmp/
          retention-days: 10

  deploy-predev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: latest-build
          path: build
      - name: Deploy to DEV (pre)
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          production-deploy: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: development
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: latest-build
          path: build
      - name: Deploy to DEV
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          github-deployment-environment: ${{ job.environment }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1


  # yaml Anchor are not yet supported. Need to duplicate the whole code for now
  deploy-qa:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: qa
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: latest-build
          path: build
      - name: Deploy to QA
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

  # yaml Anchor are not yet supported. Need to duplicate the whole code for now
  deploy-staging:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref == 'refs/heads/master'
    needs: build
    environment:
      name: staging
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: latest-build
          path: build
      - name: Deploy to Staging
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1


  # yaml Anchor are not yet supported. Need to duplicate the whole code for now
  deploy-prod:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: prod
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: latest-build
          path: build
      - name: Deploy to prod
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
